Added custom softmax layer as alternative (not working yet) AttributeError: 'Node' object has no attribute 'output_masks' on layer call (caused by topology collecting previous masks) (?)